############################################################
#
# Home Assistant Automated Configuration Backup
#
############################################################

- alias: Backup Configuration at 3am
  trigger:
    platform: time
    after: '03:00:00'
  action:
    service: shell_command.backup_config
