############################################################
#
# Home Assistant Back Lights PIR Automation 
#
############################################################

- alias: Turn ON back lights when PIR channel is ACTIVATED
  trigger:
    platform: mqtt
    topic: "house/controller/1" 
    payload: '6'
  condition:
    condition: state
    entity_id: 'sensor.light_sensor'
    state: 'Night'
  action:
    service: homeassistant.turn_on
    entity_id: script.back_lights_motion_timer
