############################################################
#
# Home Assistant Back Lights Door Automation 
#
############################################################

- alias: "Turn ON Courtyard Lights when Back Door is OPENED" 
  trigger:
    platform: state
    entity_id: 'sensor.template_back_door' 
    state: 'open'
  condition:
    condition: state
    entity_id: 'sensor.light_sensor'
    state: 'Night'
  action:
    service: homeassistant.turn_on
    entity_id: script.back_door_courtyard_lights_timer
