############################################################
#
# Home Assistant Bathroom Lights Motion Automation 
#
############################################################

- alias: Bathroom Light ON when Motion is ACTIVE
  trigger:
    platform: state
    entity_id: sensor.bathroom_motion_sensor
    to: 'Motion'
  action:
    service: script.bathroom_motion_timer
