############################################################
#
# Home Assistant Turn off CCTV Detection when
#
# Front Door is Open Automation
#
############################################################

- alias: Set CCTV Detection to OFF when Front Door OPEN
  trigger:
    platform: state
    entity_id: binary_sensor.frontdoorswitch_sensor_3_0
    state: 'on'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.cctv_disabled

############################################################
#
# Home Assistant Turn off CCTV Detection when
#
# Front Door is Open Automation
#
############################################################

- alias: Set CCTV Detection to ON when Front Door CLOSED
  trigger:
    platform: state
    entity_id: binary_sensor.frontdoorswitch_sensor_3_0
    state: 'off'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.cctv_disabled

