############################################################
#
# CCTV Detection Controls
#
############################################################

############################################################
#
# Get CCTV Intrusion Detection Status
#
############################################################

- alias: GET Intrusion Detection STATUS
  trigger:
    platform: state
    entity_id: input_boolean.cctv_disabled
    state: 'on'
  condition:
    condition: state
    entity_id: switch.cctv_intrusion_detection
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.get_intrusion_detection

############################################################
#
# Get CCTV Line Detection Status
#
############################################################

- alias: GET Line Detection STATUS
  trigger:
    platform: state
    entity_id: input_boolean.cctv_disabled
    state: 'on'
  condition:
    condition: state
    entity_id: switch.cctv_line_crossing_detection
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.get_line_detection

############################################################
#
# Get CCTV Motion Detection Status
#
############################################################

- alias: GET Motion Detection STATUS
  trigger:
    platform: state
    entity_id: input_boolean.cctv_disabled
    state: 'on'
  condition:
    condition: state
    entity_id: switch.cctv_motion
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.get_motion

############################################################
#
# Set CCTV Intrusion Detection Status
#
############################################################

- alias: SET Intrusion Detection STATUS
  trigger:
    platform: state
    entity_id: input_boolean.cctv_disabled
    state: 'off'
  condition:
    condition: state
    entity_id: input_boolean.cctv_intruder
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.set_intrusion_detection

############################################################
#
# Set CCTV Line Detection Status
#
############################################################

- alias: SET Line Detection STATUS
  trigger:
    platform: state
    entity_id: input_boolean.cctv_disabled
    state: 'off'
  condition:
    condition: state
    entity_id: input_boolean.cctv_line
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.set_line_detection

############################################################
#
# Set CCTV Motion Detection Status
#
############################################################

- alias: SET Motion Detection STATUS
  trigger:
    platform: state
    entity_id: input_boolean.cctv_disabled
    state: 'off'
  condition:
    condition: state
    entity_id: input_boolean.cctv_motion
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.set_motion
