############################################################
#
# Home Assistant Courtyard PIR Notification
#
############################################################

- alias: Notify Rasplex when Courtyard PIR channel is ACTIVATED
  trigger:
    platform: mqtt
    topic: "house/controller/1" 
    payload: '1'
  action:
    - service: notify.rasplex
      data_template:
        title: 'Alert'
        message: 'Motion detected in Courtyard'
