############################################################
#
# Home Assistant Door Doorbell Alert Automation 
#
############################################################

- alias: FLASH hue go when DOORBELL at DOOR is PRESSED
  trigger:
    platform: mqtt
    topic: "house/controller/1"
    payload: '5'
  action:
    service: homeassistant.turn_on
    entity_id: script.door_doorbell_alert_timer
     
############################################################
#
# Home Assistant Gate Doorbell Alert Automation 
#
############################################################

- alias: FLASH hue go when DOORBELL at GATE is PRESSED
  trigger:
    platform: mqtt
    topic: "house/controller/1"
    payload: '3'
  action:
    service: homeassistant.turn_on
    entity_id: script.gate_doorbell_alert_timer
