############################################################
#
# Home Assistant Driveway PIR Notification
#
############################################################

- alias: Notify Rasplex when Driveway PIR channel is ACTIVATED
  trigger:
    platform: mqtt
    topic: "house/controller/1" 
    payload: '6'
  action:
    - service: notify.rasplex
      data:
        title: 'Alert'
        message: 'Motion detected in Driveway'
