############################################################
#
# Home Assistant Front Lights PIR Automation 
#
############################################################

- alias: "Turn ON Front Lights when PIR channel is ACTIVATED"
  trigger:
    platform: mqtt
    topic: "house/controller/1" 
    payload: '4'
  condition:
    condition: state
    entity_id: 'sensor.light_sensor'
    state: 'Night'
  action:
    service: homeassistant.turn_on
    entity_id: script.front_floodlights_motion_timer

############################################################
#
# Home Assistant Front Lights Door Automation 
#
############################################################

- alias: "Turn ON Front Lights when Front Door is OPENED" 
  trigger:
    platform: state
    entity_id: binary_sensor.frontdoorswitch_sensor_3
    state: 'on'
  condition:
    condition: state
    entity_id: 'sensor.light_sensor'
    state: 'Night'
  action:
    service: homeassistant.turn_on
    entity_id: script.front_floodlights_motion_timer
