############################################################
#
# Home Assistant Front PIR Notification
#
############################################################

- alias: Notify Rasplex when Front PIR channel is ACTIVATED
  trigger:
    platform: mqtt
    topic: "house/controller/1" 
    payload: '4'
  action:
    service: notify.rasplex
    data:
      title: 'Alert'
      message: 'Motion detected out Front'
      data:
        displaytime: 30000
