############################################################
#
# Home Assistant Hall Lights Motion Automation 
#
############################################################

- alias: Hall Light ON when Motion is ACTIVE
  trigger:
    platform: state
    entity_id: sensor.hall_motion_sensor
    to: 'Motion'
  action:
    service: script.hall_motion_timer
