############################################################
#
# Home Assistant Kitchen Lights Motion Automation 
#
############################################################

- alias: Kitchen Strip Light ON when Motion is ACTIVE
  trigger:
    platform: state
    entity_id: sensor.kitchen_motion_sensor 
    to: 'Motion'
  condition:
    condition: state
    entity_id: sensor.light_sensor
    state: 'Night'
  action:
    service: script.kitchen_motion_timer
