############################################################
#
# Home Assistant Pause TV on Door Doorbell Automation 
#
############################################################

- alias: PAUSE TV when DOORBELL at DOOR is PRESSED
  trigger:
    platform: mqtt
    topic: "house/controller/1"
    payload: '5'
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.harmony
      command: Pause
      device: >
        {% if is_state("sensor.living_room_entertainment", "Watch Fire TV") %}
          42002172
        {% elif is_state("sensor.living_room_entertainment", "Watch Plex") %}
          42001332
        {% elif is_state("sensor.living_room_entertainment", "Watch TV") %}
          42001098
        {% endif %}

############################################################
#
# Home Assistant Pause TV on Gate Doorbell Automation 
#
############################################################

- alias: PAUSE TV when DOORBELL at DOOR is PRESSED
  trigger:
    platform: mqtt
    topic: "house/controller/1"
    payload: '3'
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.harmony
      command: Pause
      device: >
        {% if is_state("sensor.living_room_entertainment", "Watch Fire TV") %}
          42002172 
        {% elif is_state("sensor.living_room_entertainment", "Watch Plex") %}
          42001332 
        {% elif is_state("sensor.living_room_entertainment", "Watch TV") %}
          42001098
        {% endif %}
