############################################################
#
# Home Assistant Porch light on when Motion Automation 
#
############################################################

- alias: Porch Light ON when Motion is ACTIVE
  trigger:
    platform: state
    entity_id: sensor.porch_motion_sensor 
    to: 'Motion'
  condition:
    condition: state
    entity_id: sensor.light_sensor
    state: 'Night'
  action:
    service: script.porch_motion_timer 
