############################################################

# Home Assistant Stair Light on when Lower Motion Automation 
#
############################################################

- alias: Stairs Light ON when Lower Motion is ACTIVE
  trigger:
    - platform: state
      entity_id: sensor.lower_stairs_motion_sensor
      to: 'Motion'
  condition:
    condition: state
    entity_id: sensor.light_sensor 
    state: 'Night' 
  action:
    service: script.stairs_motion_timer

############################################################
#
# Home Assistant Stair Light on when Upper Motion Automation 
#
############################################################

- alias: Stairs Light ON when Upper Motion is ACTIVE
  trigger:
    - platform: state
      entity_id: sensor.upper_stairs_motion_sensor
      to: 'Motion'
  condition:
    condition: state
    entity_id: sensor.light_sensor 
    state: 'Night' 
  action:
    service: script.stairs_motion_timer

