############################################################
#
# Home Assistant Summer House PIR Automation 
#
############################################################

- alias: Turn ON Summer House Lights when PIR channel is ACTIVATED
  trigger:
    platform: mqtt
    topic: "house/controller/1"
    payload: "2"
  condition:
    condition: state
    entity_id: 'sensor.light_sensor'
    state: 'Night'
  action:
    service: homeassistant.turn_on
    entity_id: script.summerhouse_lights_motion_timer
