############################################################
#
# Notify Graeme when Home Assistant Update is available
#
############################################################

- alias: 'NOTIFY Graeme when UPDATE is available'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.notify_graeme
    data_template:
        message: "Home Assistant {{ states('updater.updater') }} is now available."
