############################################################
#
# Home Assistant Utility Room Lights On when Door is OPEN
#
############################################################

- alias: "Turn ON Utility Room Lights when Door is OPEN" 
  trigger:
    platform: state
    entity_id: 'sensor.template_utility_room_door'
    state: 'open'
  action:
    service: homeassistant.turn_on
    entity_id: script.utility_room_lights_timer
