############################################################
#
# Google Calendar Sensors
#
############################################################

- platform: template
  sensors:
    next_calendar_event:
      friendly_name: 'Next Event'
      value_template: '{{ states.calendar.shared.attributes.message }}'
    next_calendar_event_date:
      friendly_name: 'Time'
      value_template: '{{ states.calendar.shared.attributes.start_time }}'
