- platform: hp_ilo
  name: Server
  host: !secret hp_ilo_server
  port: 443
  username: !secret hp_ilo_username
  password: !secret hp_ilo_password
  monitored_variables:
    - server_name
    - server_fqdn
    - server_host_data
      #    - server_oa_info
    - server_power_status
      #    - server_power_readings
    - server_power_on_time
    - server_asset_tag
    - server_uid_status
    - server_health
    - network_settings

- platform: hp_ilo
  name: Media Server
  host: !secret hp_ilo_mediaserver
  port: 443
  username: !secret hp_ilo_username
  password: !secret hp_ilo_password
  monitored_variables:
    - server_name
    - server_fqdn
    - server_host_data
      #    - server_oa_info
    - server_power_status
      #    - server_power_readings
    - server_power_on_time
    - server_asset_tag
    - server_uid_status
    - server_health
    - network_settings

- platform: template
  sensors:
    server_fan:
      value_template: '{{states.sensor.media_server_server_health.attributes.fans["Fan 1"]["speed"][0] }}'
      unit_of_measurement: '%'
      entity_id: sensor.media_server_server_health
      friendly_name: "Server Fan"
