############################################################
#
# Statistics Sensor
#
############################################################

- platform: statistics
  entity_id: sensor.mainstairslower_temperature_12_1
  name: 'Living_Room_Temp_Statistics'

- platform: statistics
  entity_id: sensor.kitchenmotionsensor_temperature_2_1
  name: 'Kitchen_Temp_Statistics'

- platform: statistics
  entity_id: sensor.energy_monitor
  name: 'Energy_Monitor_Statistics'
  sampling_size: 43200
