############################################################
#
# Home Assistant Binary Sensors
#
############################################################


############################################################
#
# ISS 
#
############################################################

- platform: iss
  show_on_map: true

############################################################
#
# PIRs
#
############################################################

- platform: mqtt
  state_topic: "house/controller/1"
  name: "Front PIR"
  qos: 0
  payload_on: "4"
  payload_off: "4 off"
  sensor_class: motion

- platform: mqtt
  state_topic: "house/controller/1"
  name: "Summer House"
  qos: 0
  payload_on: "2"
  payload_off: "2 off"
  sensor_class: motion

- platform: mqtt
  state_topic: "house/controller/1"
  name: "Driveway"
  qos: 0
  payload_on: "6"
  payload_off: "6 off"
  sensor_class: motion

- platform: mqtt
  state_topic: "house/controller/1"
  name: "Courtyard"
  qos: 0
  payload_on: "1"
  payload_off: "1 off"
  sensor_class: motion


############################################################
#
# Doorbells
#
############################################################

- platform: mqtt
  state_topic: "house/controller/1"
  name: "Doorbell Gate"
  qos: 0
  payload_on: "3"
  payload_off: "3 off"
  sensor_class: "None" 

- platform: mqtt
  state_topic: "house/controller/1"
  name: "Doorbell Door"
  qos: 0
  payload_on: "5"
  payload_off: "5 off"
  sensor_class: "None" 

- platform: trend
  sensors:
    house_temp_trend:
      entity_id: sensor.house_temperature_mean
      friendly_name: 'Temperature Rising'
      sensor_class: heat

    power_trend_invert:
      entity_id: sensor.energy_monitor 
      friendly_name: 'Temperature Falling'
      sensor_class: cold
      invert: Yes


