############################################################
#
# Home Assistant Camera Configuration
#
############################################################

- platform: mjpeg
  mjpeg_url: !secret camera_mjpeg_url
  name: CCTV Front

