############################################################
#
# Home Assistant Climate Controls
#
############################################################

- platform: nest

- platform: generic_thermostat
  name: Summer House
  heater: switch.summerhousepower_switch_15
  target_sensor: sensor.summerhousedoor_temperature_13
  min_temp: 3
  max_temp: 26
  target_temp: 6
