############################################################
#
# Home Assistant Media Players
#
############################################################

- platform: plex
- platform: samsungtv
  host: 192.168.2.212 
