############################################################
#
# Home Assistant Media Players
#
############################################################

- platform: plex
  scan_interval: 3
- platform: samsungtv
  host: 192.168.2.212 
